import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import { PersonaProvider } from "@/components/providers/persona-provider";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      {/* h-dvh, not min-h-full: min-height let the body grow with the
          conversation, so `flex-1` never resolved to a bounded height, the
          message scroller's overflow-y-auto never engaged, and the whole
          document scrolled instead — pushing the composer off the bottom of
          the screen. A definite viewport height is what makes the chat scroll
          inside itself. h-dvh over h-screen so mobile URL-bar resize doesn't
          clip it. overflow-hidden stops a second, document-level scrollbar. */}
      <body className="flex h-dvh flex-col overflow-hidden">
        <ClerkProvider>
          <TooltipProvider>
            <PersonaProvider>{children}</PersonaProvider>
          </TooltipProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
